server:
  port: 8888

spring:
  application:
    name: service-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
      mybatis: ERROR
  path: D:/logs/server.log
#  file: ./logs/server.log