spring:
  application:
    name: service-user
  zipkin:
    base-url: http://localhost:8769
  sleuth:
    sampler:
      percentage: 1

server:
  port: 8762

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
      mybatis: ERROR
#    path: D:/temp/logs/service-user-zipkin.log
#  file: ./logs/service-user.log